#!/usr/bin/env python3
"""
SP-API auth diagnostic.

Calls the Sellers API getMarketplaceParticipations operation, which requires
NO special role. It reuses the exact credentials from upload_listings.py.

Interpreting the result:
  * Prints marketplaces  -> token + account are valid; a 403 on Listings means
    the app is missing the "Product Listing" role (re-authorize after adding it).
  * 403 here too         -> the app authorization itself is wrong: either the
    refresh token was issued by a different selling account than SELLER_ID, or
    the app is not authorized for this seller at all.
"""

from sp_api.api import Sellers, ListingsItems
from sp_api.base import SellingApiException

# Reuse the same credentials/marketplace already configured in the uploader.
from upload_listings import SP_API_CREDENTIALS, MARKETPLACE, SELLER_ID, MARKETPLACE_ID

print(f"Configured SELLER_ID : {SELLER_ID}")
print(f"Marketplace          : {MARKETPLACE.name} ({MARKETPLACE.marketplace_id})")
print("Calling Sellers.getMarketplaceParticipations ...\n")

try:
    res = Sellers(credentials=SP_API_CREDENTIALS, marketplace=MARKETPLACE).get_marketplace_participation()
    payload = res.payload or []
    print("SUCCESS — token can read this account. Marketplaces you participate in:\n")
    for entry in payload:
        mp = entry.get("marketplace", {})
        part = entry.get("participation", {})
        print(
            f"  - {mp.get('name'):<25} id={mp.get('id'):<16} "
            f"country={mp.get('countryCode')} selling={part.get('isParticipating')}"
        )
    ids = [e.get("marketplace", {}).get("id") for e in payload]
    print()
    if "A1F83G8C2ARO7P" in ids:
        print(">> UK (A1F83G8C2ARO7P) IS accessible. The Listings 403 is a ROLE problem:")
        print(">> add the 'Product Listing' role to the app, then RE-AUTHORIZE for a new token.")
    else:
        print(">> UK (A1F83G8C2ARO7P) is NOT in your accessible marketplaces.")
        print(">> This account cannot list on Amazon UK with this authorization.")
except SellingApiException as exc:
    print("FAILED — Sellers API was denied too:\n")
    print(f"  {exc}\n")
    print(">> Auth works but this app/token has NO access to the account.")
    print(">> Likely causes: (1) the refresh token was generated by a DIFFERENT")
    print(">> selling account than SELLER_ID, or (2) the app is not authorized")
    print(">> for this seller. Verify the merchant token in Seller Central ->")
    print(">> Settings -> Account Info, and that you authorized THIS app with THAT account.")


# -----------------------------------------------------------------------------
# Step 2: read-only Listings check — proves whether the token carries the
# "Product Listing" role WITHOUT creating or changing any live listing.
# getListingsItem needs the SAME role as the write (putListingsItem), so:
#   200 / 404  -> role IS on the token; the uploader will work.
#   403        -> role is still missing; re-add it and RE-AUTHORIZE for a new token.
# -----------------------------------------------------------------------------
TEST_SKU = "HAJJ-LUX-10GB-30D"   # any SKU works; 404 just means "not found yet"
print("\n" + "=" * 70)
print(f"Read-only Listings role check (getListingsItem, sku={TEST_SKU}) ...\n")
try:
    ListingsItems(credentials=SP_API_CREDENTIALS, marketplace=MARKETPLACE).get_listings_item(
        sellerId=SELLER_ID,
        sku=TEST_SKU,
        marketplaceIds=[MARKETPLACE_ID],
    )
    print("SUCCESS (200) — token HAS the Product Listing role. Uploader will work.")
except SellingApiException as exc:
    code = getattr(exc, "code", None)
    if code == 404:
        print("OK (404 not found) — token HAS the Product Listing role.")
        print(">> 404 just means this SKU isn't listed yet. The uploader will work.")
    elif code == 403:
        print("403 DENIED — token does NOT have the Product Listing role yet.")
        print(">> Add 'Product Listing' to the app -> Save -> wait -> RE-AUTHORIZE")
        print(">> -> use the NEW refresh token. (Old tokens never gain new roles.)")
    else:
        print(f"Unexpected error: {exc}")
